name: Check Images

on: [push, pull_request]

jobs:
  check-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Check for image files and size
      run: 
       find ./imagehub -type f ! -size -2M -exec echo "Found a file larger than 1MB:" {} \; -exec false {} +
